// Stories are token-aligned so every English unit has a French counterpart.
// Where word order differs, the whole phrase is one morphing unit
// (e.g. "wise owl" ↔ "chouette sage"). Punctuation stays attached.
// A token of { br: true } forces a line break (used in verse).
// An optional `synonyms: [...]` list gives a token a same-language chain of
// near-synonyms (e.g. cold -> freezing -> harsh -> ...); ambient drift will
// sometimes wander through that chain instead of flipping EN/FR.

export const stories = [
  {
    id: 'fox',
    genre: { en: 'a fable', fr: 'une fable' },
    title: { en: 'The Fox and the Moon', fr: 'Le renard et la lune' },
    paragraphs: [
      [
        { en: 'One', fr: 'Un' },
        { en: 'evening,', fr: 'soir,' },
        { en: 'a', fr: 'un' },
        { en: 'little', fr: 'petit' },
        { en: 'fox', fr: 'renard' },
        { en: 'found', fr: 'trouva' },
        { en: 'the', fr: 'la' },
        { en: 'moon', fr: 'lune' },
        { en: 'in', fr: 'dans' },
        { en: 'the', fr: 'la' },
        { en: 'river.', fr: 'rivière.' },
        { en: 'He', fr: 'Il' },
        { en: 'wanted', fr: 'voulait' },
        { en: 'to drink', fr: 'boire' },
        { en: 'the', fr: 'la' },
        { en: 'light.', fr: 'lumière.' },
        { en: '“Come', fr: '« Viens' },
        { en: 'here,”', fr: 'ici »,' },
        { en: 'he said,', fr: 'dit-il,' },
        { en: '“you', fr: '« tu' },
        { en: 'are', fr: 'es' },
        { en: 'so', fr: 'si' },
        { en: 'beautiful.”', fr: 'belle. »' },
        { en: 'But', fr: 'Mais' },
        { en: 'the water', fr: 'l’eau' },
        { en: 'broke', fr: 'brisa' },
        { en: 'his', fr: 'son' },
        { en: 'dream', fr: 'rêve' },
        { en: 'into', fr: 'en' },
        { en: 'a thousand', fr: 'mille' },
        { en: 'pieces.', fr: 'morceaux.' },
      ],
      [
        { en: 'The', fr: 'La' },
        { en: 'wise owl', fr: 'chouette sage' },
        { en: 'watched', fr: 'regardait' },
        { en: 'from', fr: 'depuis' },
        { en: 'an', fr: 'un' },
        { en: 'old', fr: 'vieux' },
        { en: 'oak.', fr: 'chêne.' },
        { en: '“Little', fr: '« Petit' },
        { en: 'friend,”', fr: 'ami »,' },
        { en: 'she said,', fr: 'dit-elle,' },
        { en: '“the', fr: '« la' },
        { en: 'moon', fr: 'lune' },
        { en: 'lives', fr: 'habite' },
        { en: 'in the sky.”', fr: 'dans le ciel. »' },
        { en: 'The', fr: 'La' },
        { en: 'river', fr: 'rivière' },
        { en: 'only carries', fr: 'ne porte que' },
        { en: 'her', fr: 'son' },
        { en: 'reflection.', fr: 'reflet.' },
      ],
      [
        { en: 'The', fr: 'Le' },
        { en: 'fox', fr: 'renard' },
        { en: 'looked up', fr: 'leva les yeux' },
        { en: 'and', fr: 'et' },
        { en: 'smiled.', fr: 'sourit.' },
        { en: 'Some', fr: 'Certains' },
        { en: 'treasures', fr: 'trésors' },
        { en: 'are', fr: 'sont' },
        { en: 'more beautiful', fr: 'plus beaux' },
        { en: 'when', fr: 'quand' },
        { en: 'they', fr: 'ils' },
        { en: 'stay', fr: 'restent' },
        { en: 'far away.', fr: 'loin.' },
      ],
    ],
  },
  {
    id: 'signal',
    genre: { en: 'science fiction', fr: 'science-fiction' },
    title: { en: 'The Last Signal', fr: 'Le dernier signal' },
    paragraphs: [
      [
        { en: 'The', fr: 'La' },
        { en: 'station', fr: 'station' },
        { en: 'orbited', fr: 'tournait autour' },
        { en: 'a dying star.', fr: 'd’une étoile mourante.' },
        { en: 'Every', fr: 'Chaque' },
        { en: 'morning,', fr: 'matin,' },
        { en: 'Mira', fr: 'Mira' },
        { en: 'listened to', fr: 'écoutait' },
        { en: 'the', fr: 'le' },
        { en: 'silence', fr: 'silence' },
        { en: 'between', fr: 'entre' },
        { en: 'the', fr: 'les' },
        { en: 'planets.', fr: 'planètes.' },
      ],
      [
        { en: 'One', fr: 'Une' },
        { en: 'night,', fr: 'nuit,' },
        { en: 'a', fr: 'un' },
        { en: 'signal', fr: 'signal' },
        { en: 'arrived.', fr: 'arriva.' },
        { en: 'Three', fr: 'Trois' },
        { en: 'notes,', fr: 'notes,' },
        { en: 'repeated,', fr: 'répétées,' },
        { en: 'like', fr: 'comme' },
        { en: 'a', fr: 'un' },
        { en: 'heartbeat.', fr: 'battement de cœur.' },
        { en: 'It', fr: 'Il' },
        { en: 'came', fr: 'venait' },
        { en: 'from', fr: 'de la' },
        { en: 'Earth,', fr: 'Terre,' },
        { en: 'a', fr: 'un' },
        { en: 'world', fr: 'monde' },
        { en: 'that', fr: 'qui' },
        { en: 'no longer existed.', fr: 'n’existait plus.' },
      ],
      [
        { en: 'Mira', fr: 'Mira' },
        { en: 'smiled', fr: 'sourit' },
        { en: 'and', fr: 'et' },
        { en: 'pressed', fr: 'appuya sur' },
        { en: 'the red button.', fr: 'le bouton rouge.' },
        { en: '“Hello,”', fr: '« Bonjour »,' },
        { en: 'she whispered,', fr: 'murmura-t-elle,' },
        { en: '“we', fr: '« nous' },
        { en: 'are', fr: 'sommes' },
        { en: 'still', fr: 'toujours' },
        { en: 'here.”', fr: 'là. »' },
      ],
    ],
  },
  {
    id: 'umbrella',
    genre: { en: 'a mystery', fr: 'un polar' },
    title: { en: 'The Umbrella Thief', fr: 'Le voleur de parapluies' },
    paragraphs: [
      [
        { en: 'It', fr: 'Il' },
        { en: 'always rained', fr: 'pleuvait toujours' },
        { en: 'on', fr: 'sur' },
        { en: 'Harbor Street.', fr: 'la rue du Port.' },
        { en: 'Detective', fr: 'L’inspectrice' },
        { en: 'Malou', fr: 'Malou' },
        { en: 'counted', fr: 'comptait' },
        { en: 'the', fr: 'les' },
        { en: 'umbrellas', fr: 'parapluies' },
        { en: 'from', fr: 'depuis' },
        { en: 'her', fr: 'sa' },
        { en: 'window.', fr: 'fenêtre.' },
      ],
      [
        { en: 'Every', fr: 'Chaque' },
        { en: 'Tuesday,', fr: 'mardi,' },
        { en: 'one of them', fr: 'l’un d’eux' },
        { en: 'disappeared.', fr: 'disparaissait.' },
        { en: 'Never', fr: 'Jamais' },
        { en: 'the new ones,', fr: 'les neufs,' },
        { en: 'only', fr: 'seulement' },
        { en: 'the old,', fr: 'les vieux,' },
        { en: 'faithful,', fr: 'fidèles,' },
        { en: 'broken ones.', fr: 'cassés.' },
      ],
      [
        { en: 'On', fr: 'Sur' },
        { en: 'the', fr: 'le' },
        { en: 'roof,', fr: 'toit,' },
        { en: 'she', fr: 'elle' },
        { en: 'found', fr: 'trouva' },
        { en: 'the', fr: 'le' },
        { en: 'thief:', fr: 'voleur :' },
        { en: 'a', fr: 'une' },
        { en: 'magpie,', fr: 'pie,' },
        { en: 'and', fr: 'et' },
        { en: 'a', fr: 'un' },
        { en: 'nest', fr: 'nid' },
        { en: 'built', fr: 'fait' },
        { en: 'of', fr: 'de' },
        { en: 'black silk.', fr: 'soie noire.' },
        { en: 'Some', fr: 'Certains' },
        { en: 'mysteries', fr: 'mystères' },
        { en: 'prefer', fr: 'préfèrent' },
        { en: 'to stay', fr: 'rester' },
        { en: 'small.', fr: 'petits.' },
      ],
    ],
  },
  {
    id: 'autumn',
    genre: { en: 'a poem', fr: 'un poème' },
    title: { en: 'Autumn Song', fr: 'Chanson d’automne' },
    verse: true,
    paragraphs: [
      [
        { en: 'The', fr: 'Les' },
        { en: 'leaves', fr: 'feuilles' },
        { en: 'are', fr: 'sont' },
        { en: 'letters', fr: 'des lettres' },
        { br: true },
        { en: 'the wind', fr: 'que le vent' },
        { en: 'writes', fr: 'écrit' },
        { en: 'to the ground.', fr: 'au sol.' },
        { br: true },
        { en: 'Gold,', fr: 'Or,' },
        { en: 'rust,', fr: 'rouille' },
        { en: 'and', fr: 'et' },
        { en: 'amber,', fr: 'ambre,' },
        { br: true },
        { en: 'falling', fr: 'tombant' },
        { en: 'without', fr: 'sans' },
        { en: 'a', fr: 'un' },
        { en: 'sound.', fr: 'bruit.' },
      ],
      [
        {
          en: 'Winter',
          fr: 'L’hiver',
          synonyms: ['Cold', 'Freezing', 'Harsh', 'Brisk', 'Chilly', 'Polar', 'Arctic', 'Icy'],
        },
        { en: 'will read them', fr: 'les lira' },
        { br: true },
        { en: 'slowly,', fr: 'lentement,' },
        { en: 'one by one,', fr: 'une à une,' },
        { br: true },
        { en: 'and', fr: 'et' },
        { en: 'keep', fr: 'gardera' },
        { en: 'the sweetest words', fr: 'les mots les plus doux' },
        { br: true },
        { en: 'for', fr: 'pour' },
        { en: 'the return', fr: 'le retour' },
        { en: 'of the sun.', fr: 'du soleil.' },
      ],
    ],
  },
];

// User-written stories live as JSON files in src/stories/user/ - one story
// per file, written there by the dev-server editor (the "+" in the library)
// or dropped in by hand. Same token format as above, except the text lives
// under `pages` (an array of paragraph lists): one page = a story, several
// pages = a book the reader can leaf through.
const userModules = import.meta.glob('./stories/user/*.json', { eager: true });

export const userStories = Object.keys(userModules)
  .sort()
  .map((path) => userModules[path].default);

export const allStories = [...stories, ...userStories];

// Built-in stories keep a flat `paragraphs` list; books have `pages`.
export function pagesOf(story) {
  return story.pages || [story.paragraphs];
}
